version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      VETPATHOGEN_DATABASE_URL: sqlite:///data/vetpathogen.db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - backend-data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["python", "-m", "backend.job_runner"]
    environment:
      VETPATHOGEN_DATABASE_URL: sqlite:///data/vetpathogen.db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - backend-data:/app/data
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://backend:8000
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - worker

volumes:
  backend-data:
    driver: local
